name: Dependencies - OWASP DC (HTML + Threshold)

on:
  push:
    branches: [ main, fix/**, feature/** ]
    paths:
      - '**/*.csproj'
      - '**/packages.config'
      - '.github/workflows/03-deps-owasp-dependency-check-html.yml'
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 7 * * 1"  # Lunes 07:00 UTC
  workflow_dispatch:

env:
  FAIL_ON_CVSS: "7.0"    # Umbral configurable desde aquí

jobs:
  depcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Dependency-Check usa Java (incluido en ubuntu-latest)
      # Mantén su data cacheada para acelerar:
      - name: Cache DC Data
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository/org/owasp/dependency-check-data
          key: odc-data-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
          restore-keys: odc-data-${{ runner.os }}-

      - name: OWASP Dependency-Check (HTML)
        uses: dependency-check/Dependency-Check_Action@v4.0.1
        with:
          project: "Facturacion-Ropa-Intima-Orozco"
          path: "."
          format: "HTML"
          out: "dc-report"
          args: >
            --scan .
            --disableAssembly
            --failOnCVSS ${{ env.FAIL_ON_CVSS }}

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-html
          path: dc-report/dependency-check-report.html
