name: Repo Scan - Trivy FS (HTML/JSON + Threshold)

on:
  push:
    branches: [ main, fix/**, feature/** ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 8 * * 1" # Lunes 08:00 UTC
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  actions: read

env:
  TRIVY_TIMEOUT: 10m
  TRIVY_SEVERITY: CRITICAL,HIGH
  TRIVY_EXIT_CODE: 0             #  No detiene el flujo si hay vulnerabilidades
  TRIVY_IGNORE_UNFIXED: true
  TRIVY_CACHE_DIR: ~/.cache/trivy

jobs:
  trivy-fs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Trivy DB
        uses: actions/cache@v4
        with:
          path: ~/.cache/trivy
          key: trivy-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: trivy-${{ runner.os }}-

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.54.1_Linux-64bit.deb
          sudo dpkg -i trivy_0.54.1_Linux-64bit.deb

      - name: Trivy FS → JSON (para consolidación)
        run: trivy fs . --format json -o trivy-report.json || true

      - name: Trivy FS → HTML (para lectura humana)
        run: |
          trivy fs . --format template --template "@contrib/html.tpl" -o trivy-report.html || true

      - name: Subir artefactos
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: |
            trivy-report.html
            trivy-report.json

      - name: Mostrar resumen del análisis
        run: |
          echo " Reportes generados:"
          echo "- HTML: trivy-report.html"
          echo "- JSON: trivy-report.json"
